### ISSUE TITLE
Markers misplaced on Flipped ruler

### ISSUE THREAD

**Issue by dkloke** [Bluegrams/ScreenRuler#42]
Thank you for this elegant and useful tool.

However, when the ruler is in flipped modes, markers appear in incorrect positions. Also, trying to close "Edit Markers" windowlet can crash program after "Clear All Markers" is invoked while windowlet is open.

[EDIT] Version: This report applies to version 0.9.0.

Reproduce error:
- Clear all Markers.
- Put ruler in "un-flipped" position, with origin at upper left
- Confirm correct marker function with a couple of markers.
- Flip ruler horizontally, existing markers are correctly transposed.
- Newly set markers appear in the inverse position from their placement.
- Flip ruler horizontally (back to initial). Existing markers are preserved and transposed, and new markers are correctly placed.

Similar behavior with vertical ruler.

When two-dimensional ruler is set, and one or both axes are flipped, markers set on the horizontal axis appear on the vertical axis, not clearly corresponding to intended horizontal position. Vertical axis markers don't place at all, or sometimes appear on the horizontal axis.

To reproduce the Edit Marker windowlet behavior:
- Set some markers.
- Open the Edit Markers windowlet.
- Invoke Clear All Markers.
- Try to close the Markers windowlet. App throws error: 
```
InvalidArgument=Value of '-1' is not valid for 'index'
Parameter name: index
```
(See full details at end of post)

Expected behavior:
- Markers are correctly placed on the correct axis when ruler is in flipped modes.
- Edit Markers windowlet closes when last marker is deleted, or survives being emptied.

Flipping the ruler, especially in combination with the two-axis mode, is one of the most useful features of the app, I hope it can be preserved. Thank you again for this program.

Error details (for Markers windowlet):
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListBox.ObjectCollection.get_Item(Int32 index)
   at ScreenRuler.Controls.MarkerListBox.OnDrawItem(DrawItemEventArgs e)
   at System.Windows.Forms.ListBox.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
screenruler
    Assembly Version: 0.9.0.0
    Win32 Version: 0.9.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/screenruler/tools/screenruler/screenruler.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
CommandLine
    Assembly Version: 2.8.0.0
    Win32 Version: 0.9.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/screenruler/tools/screenruler/screenruler.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AppHelpers.WinForms
    Assembly Version: 0.1.0.11
    Win32 Version: 0.9.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/screenruler/tools/screenruler/screenruler.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PortableSettingsProvider
    Assembly Version: 0.2.3.0
    Win32 Version: 0.9.0
    CodeBase: file:///C:/ProgramData/chocolatey/lib/screenruler/tools/screenruler/screenruler.exe
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by alxnull** [comment]
Hi @dkloke, thank you very much for the very detailed bug reports! I'll try to look into them and fix them as soon as possible.

**Comment by alxnull** [comment]
Both bugs have been fixed in v.0.9.1. I will close this issue now, please feal free to reopen if something still doesn't work as expected. Thanks!
